name: Build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Build
        run: |
          wget https://tgdl.eu.org/105689/u2net.onnx?hash=2a8857 -O u2net.onnx
